language: node_js
sudo: false
node_js:
  - 11
  - 8
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test:coverage
after-success:
  - mv coverage/coverage-final.json coverage/coverage.json
  - codecov
