language: node_js
sudo: false
node_js:
  - 11
  - 8
install:
  - npm install
  - npm install -save-dev codecov
script:
  - npm run test:coverage
  - mv coverage/coverage-final.json coverage/coverage.json
  - npm run codecov
